apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: zzqoix94k-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: zzqoix94k-nodejs 
  name: zzqoix94k-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: zzqoix94k-nodejs 
